import {
  User,
  Project,
  Task,
  BudgetCategory,
  Expense,
  Professional,
} from "@/types";

// ============ USERS ============
export const currentUser: User = {
  id: "u1",
  name: "Dely Navarro",
  initials: "DN",
  role: "owner",
  email: "dely@obraya.com",
  avatar_color: "bg-brand-500",
};

export const teamMembers: User[] = [
  {
    id: "u2",
    name: "Juan Ramirez",
    initials: "JR",
    role: "contractor",
    email: "juan@obraya.com",
    avatar_color: "bg-success-500",
  },
  {
    id: "u3",
    name: "Maria Castillo",
    initials: "MC",
    role: "architect",
    email: "maria@obraya.com",
    avatar_color: "bg-info-500",
  },
  {
    id: "u4",
    name: "Pedro Lopez",
    initials: "PL",
    role: "contractor",
    email: "pedro@obraya.com",
    avatar_color: "bg-danger-500",
  },
];

// ============ PROJECTS ============
export const projects: Project[] = [
  {
    id: "p1",
    name: "Casa Familia Lopez",
    type: "Residencial",
    area: "180m²",
    location: "Col. Del Valle",
    budget: 850000,
    spent: 623500,
    progress: 75,
    status: "on_track",
    start_date: "2026-01-15",
    end_date: "2026-06-30",
    team: [currentUser, teamMembers[0], teamMembers[1], teamMembers[2]],
  },
  {
    id: "p2",
    name: "Edificio Reforma 45",
    type: "Comercial",
    area: "1,200m²",
    location: "Paseo de la Reforma",
    budget: 4200000,
    spent: 4536000,
    progress: 42,
    status: "at_risk",
    start_date: "2026-02-01",
    end_date: "2026-11-30",
    team: [currentUser, teamMembers[0]],
  },
  {
    id: "p3",
    name: "Remodelacion Oficinas TechCo",
    type: "Corporativo",
    area: "500m²",
    location: "Santa Fe",
    budget: 1100000,
    spent: 1045000,
    progress: 90,
    status: "on_track",
    start_date: "2025-11-01",
    end_date: "2026-05-15",
    team: [teamMembers[1], teamMembers[2]],
  },
  {
    id: "p4",
    name: "Plaza Comercial Sur",
    type: "Comercial",
    area: "3,000m²",
    location: "Tlalpan",
    budget: 8500000,
    spent: 1275000,
    progress: 15,
    status: "delayed",
    start_date: "2026-03-01",
    end_date: "2027-03-31",
    team: [currentUser, teamMembers[0], teamMembers[2]],
  },
];

// ============ TASKS ============
export const tasks: Task[] = [
  // Backlog
  {
    id: "t1",
    title: "Instalar ventanas PB",
    project_id: "p1",
    status: "backlog",
    priority: "medium",
    assigned_to: teamMembers[0],
    due_date: "2026-04-15",
  },
  {
    id: "t2",
    title: "Pintura exterior fachada",
    project_id: "p1",
    status: "backlog",
    priority: "low",
    assigned_to: teamMembers[1],
    due_date: "2026-04-22",
  },
  {
    id: "t3",
    title: "Revision instalacion electrica",
    project_id: "p1",
    status: "backlog",
    priority: "high",
    assigned_to: teamMembers[2],
    due_date: "2026-04-12",
  },
  {
    id: "t4",
    title: "Solicitar piso ceramico",
    project_id: "p1",
    status: "backlog",
    priority: "low",
    assigned_to: currentUser,
    due_date: "2026-04-18",
  },
  // In Progress
  {
    id: "t5",
    title: "Plomeria banos 2do piso",
    project_id: "p1",
    status: "in_progress",
    priority: "high",
    assigned_to: teamMembers[0],
    due_date: "2026-04-10",
    progress: 60,
  },
  {
    id: "t6",
    title: "Impermeabilizacion azotea",
    project_id: "p1",
    status: "in_progress",
    priority: "medium",
    assigned_to: teamMembers[1],
    due_date: "2026-04-14",
    progress: 30,
  },
  {
    id: "t7",
    title: "Acabados cocina integral",
    project_id: "p1",
    status: "in_progress",
    priority: "medium",
    assigned_to: currentUser,
    due_date: "2026-04-08",
    progress: 80,
  },
  // Review
  {
    id: "t8",
    title: "Cimentacion losa PA",
    project_id: "p1",
    status: "review",
    priority: "high",
    assigned_to: teamMembers[2],
    due_date: "2026-04-05",
  },
  {
    id: "t9",
    title: "Instalacion gas natural",
    project_id: "p1",
    status: "review",
    priority: "medium",
    assigned_to: teamMembers[0],
    due_date: "2026-04-06",
  },
  // Done
  {
    id: "t10",
    title: "Excavacion y nivelacion",
    project_id: "p1",
    status: "done",
    priority: "high",
    assigned_to: teamMembers[0],
    due_date: "2026-04-02",
    completed_date: "2026-04-02",
  },
  {
    id: "t11",
    title: "Estructura metalica PB",
    project_id: "p1",
    status: "done",
    priority: "high",
    assigned_to: teamMembers[1],
    due_date: "2026-04-05",
    completed_date: "2026-04-05",
  },
  {
    id: "t12",
    title: "Muros de block 1er piso",
    project_id: "p1",
    status: "done",
    priority: "medium",
    assigned_to: teamMembers[2],
    due_date: "2026-04-07",
    completed_date: "2026-04-07",
  },
];

// ============ BUDGET ============
export const budgetCategories: BudgetCategory[] = [
  {
    id: "bc1",
    name: "Estructura",
    budgeted: 250000,
    spent: 237500,
    color: "bg-danger-500",
  },
  {
    id: "bc2",
    name: "Albanileria",
    budgeted: 150000,
    spent: 117000,
    color: "bg-brand-500",
  },
  {
    id: "bc3",
    name: "Plomeria",
    budgeted: 90000,
    spent: 58500,
    color: "bg-info-500",
  },
  {
    id: "bc4",
    name: "Electricidad",
    budgeted: 80000,
    spent: 88000,
    color: "bg-danger-500",
  },
  {
    id: "bc5",
    name: "Acabados",
    budgeted: 150000,
    spent: 67500,
    color: "bg-success-500",
  },
  {
    id: "bc6",
    name: "Permisos",
    budgeted: 30000,
    spent: 30000,
    color: "bg-dark-600",
  },
  {
    id: "bc7",
    name: "Imprevistos",
    budgeted: 50000,
    spent: 25000,
    color: "bg-success-500",
  },
];

export const recentExpenses: Expense[] = [
  {
    id: "e1",
    date: "2026-04-11",
    concept: "Cable electrico calibre 12 (200m)",
    category: "Electricidad",
    amount: 4800,
    registered_by: "Pedro L.",
  },
  {
    id: "e2",
    date: "2026-04-10",
    concept: "Tuberia PVC 4\" (lote)",
    category: "Plomeria",
    amount: 3200,
    registered_by: "Juan R.",
  },
  {
    id: "e3",
    date: "2026-04-09",
    concept: "Jornales albanileria semana 14",
    category: "Albanileria",
    amount: 12000,
    registered_by: "Marco C.",
  },
  {
    id: "e4",
    date: "2026-04-08",
    concept: "Cemento 50kg x30 bultos",
    category: "Albanileria",
    amount: 5400,
    registered_by: "Juan R.",
  },
  {
    id: "e5",
    date: "2026-04-07",
    concept: "Pintura interior (20L x5)",
    category: "Acabados",
    amount: 7500,
    registered_by: "Maria C.",
  },
];

// ============ PROFESSIONALS ============
export const professionals: Professional[] = [
  {
    id: "pr1",
    name: "Juan Ramirez",
    initials: "JR",
    specialty: "Maestro de Obra General",
    rating: 4.9,
    reviews: 47,
    projects_count: 85,
    years_experience: 12,
    tags: ["Albanileria", "Estructura"],
    avatar_color: "bg-info-500",
    location: "CDMX Sur",
  },
  {
    id: "pr2",
    name: "Maria Castillo",
    initials: "MC",
    specialty: "Arquitecta Interiorista",
    rating: 4.7,
    reviews: 32,
    projects_count: 45,
    years_experience: 8,
    tags: ["Diseno", "Acabados"],
    avatar_color: "bg-success-500",
    location: "CDMX Poniente",
  },
  {
    id: "pr3",
    name: "Pedro Lopez",
    initials: "PL",
    specialty: "Ingeniero Electrico",
    rating: 5.0,
    reviews: 28,
    projects_count: 60,
    years_experience: 15,
    tags: ["Electricidad", "Domotica"],
    avatar_color: "bg-danger-500",
    location: "CDMX Norte",
  },
  {
    id: "pr4",
    name: "Ana Garcia",
    initials: "AG",
    specialty: "Plomera Certificada",
    rating: 4.6,
    reviews: 19,
    projects_count: 35,
    years_experience: 6,
    tags: ["Plomeria", "Gas"],
    avatar_color: "bg-brand-500",
    location: "CDMX Centro",
  },
  {
    id: "pr5",
    name: "Roberto Mendez",
    initials: "RM",
    specialty: "Herrero Industrial",
    rating: 4.8,
    reviews: 38,
    projects_count: 52,
    years_experience: 10,
    tags: ["Herreria", "Soldadura"],
    avatar_color: "bg-dark-700",
    location: "Estado de Mexico",
  },
  {
    id: "pr6",
    name: "Laura Torres",
    initials: "LT",
    specialty: "Impermeabilizadora",
    rating: 4.5,
    reviews: 15,
    projects_count: 28,
    years_experience: 5,
    tags: ["Impermeabilizacion", "Azoteas"],
    avatar_color: "bg-warning-500",
    location: "CDMX Sur",
  },
];
